[package]
name = "c8d"
version = "0.1.0"
authors = ["Cristi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decoder = { path = "../decoder" }
clap = "2.33.3"
