[package]
name = "instruction_emulator"
version = "0.1.0"
authors = ["Cristi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
decoder = { path = "../decoder" }
